//a class is container of the code. We can call it again and again.
//
public class FirstProgram {
	//for now - we will write all the code INSIDE the method.
	//a method means function (in JS)
	
    //how to write a method?
    public static void firstMethod(){
        //method body.
        system.debug('Hello hello - we are inside firstMethod of FirstProgram');
    }
    
    public static void secondMethod(){
        
    }
    
}